### ISSUE TITLE
update vega-lite library and examples to v5.1.1

### ISSUE THREAD

**Issue by real-iceman** [RandomFractals/vscode-vega-viewer#121]
Hi there, thanks for your great extension which is very handy for editing vega specs!
I'm a vega-lite beginner and currently I am struggling a little bit with having only vega-lite v4 available in the extension whereas the online documentation for vega-lite covers only the latest version v5.

Would it be possible to update vega-lite and examples to v5?

**Comment by rafael78co** [comment]
Hello, I am in the same situation, I use the VSCode Vega Viewer to do my vega-lite specs everyday and the update to v5 is a need.

**Comment by RandomFractals** [comment]
I'll try to find the time and update those dependencies and built-in vega and vega-lite examples this month.

I was not planning on maintaining this extension due to limited user base and lack of reviews.

If you'd like to see it updated soon, please post some reviews and feedback on why and how you use it in marketplace:

https://marketplace.visualstudio.com/items?itemName=RandomFractalsInc.vscode-vega-viewer&ssr=false#review-details

Thanks!

**Comment by real-iceman** [comment]
Done ;-)

Of course you are in no way obligated to maintain this extension any longer.

In the meantime I have learned that vega-lite v4 docs are still available on [https://vega.github.io/vega-lite-v4/](https://vega.github.io/vega-lite-v4/).

**Comment by rafael78co** [comment]
Hi Novak, 
do you have some news about the update to v5 ?

**Comment by RandomFractals** [comment]
vega-lite v5? nope. I don't maintain their library. You can check their slack: https://communityinviter.com/apps/vega-js/join

or did you mean release 71 of this extension?

I will try to find the time and update this extension later this month with the latest vega and vega-lite libs and examples.

I checked their slack recently, other than here, nobody else expressed interest in those updates.

**Comment by RandomFractals** [comment]
tbh, anyone should be able to do it in a few hours. just check the last release I packaged and follow those update steps:

https://github.com/RandomFractals/vscode-vega-viewer/releases

**Comment by rafael78co** [comment]
sorry, I mean update this extension to latest Vega and Vega-Lite libs. 
would be great to have your collaboration.
thanks in advance

**Comment by RandomFractals** [comment]
see: https://github.com/vega/vega-lite/releases/tag/v5.1.0

**Comment by RandomFractals** [comment]
Looks like the latest vega-lite version with some bug fixes is v5.1.1: https://github.com/vega/vega-lite/releases/tag/v5.1.1

That would be the version I update to around holidays this or next month.

Apologies for the delays on this. It's been a very busy year on custom vscode extensions and renderers 🙂

**Comment by rafael78co** [comment]
I would like to thank you for this new update. This really impact my work because I use your extension as my regular tool to create visualization and visual data analysis. Thanks !!

**Comment by RandomFractals** [comment]
@rafael78co It was long overdue. I am just happy some devs use it.

btw, I did not do any thorough testing of new examples and other hooks this extension has. 

Please log issues if you encounter some new rough edges in this update.
