### ISSUE TITLE
Publish to Open VSX Registry?

### ISSUE THREAD

**Issue by nsajko** [RandomFractals/vscode-vega-viewer#140]
AFAIK this extension is currently only available on Microsoft's VS Code Marketplace. This is problematic because Microsoft forbids using the Marketplace from anything else than their own build of VS Code.

An alternative, more open, marketplace is used by alternative builds and forks of Code:

https://open-vsx.org

It would be super nice if you could publish the extension to the Open VSX Registry, so we who use Code, but not VS Code, could use your extension legally and without having to install and update it manually.

In case you decide to do this, here's two links that seem like they could be helpful:

https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

https://github.com/open-vsx/publish-extensions

**Comment by RandomFractals** [comment]
Hi @nsajko,

There are a couple of data extensions I published to Open VSX Registry. See [Data Preview and Geo Data Viewer](https://open-vsx.org/?search=data&category=&sortBy=relevance&sortOrder=desc)

So, I am familiar with the process and already have the verified publisher account established there. You did not have to provide all that info.

However, Open VSX Registry doesn't provide good downloads tracking options and does require some additional testing in VSCodium and other VSCode based IDEs.

Therefore, moving forward, I don't plan to publish my extensions to Open VSX Registry until the download counters in that marketplace provide accurate information.

I have been attaching `.vsix` extension package binaries to all of my latest vscode extension releases. 

You can install them from release tags. See: https://github.com/RandomFractals/vscode-vega-viewer/releases/tag/v9.5.0
