### ISSUE TITLE
"data" outside top-level specification

### ISSUE THREAD

**Issue by Corvince** [RandomFractals/vscode-vega-viewer#15]
If I load local data on the top-level of a spec it works fine, but if "data" appears somewhere else it doesn't work.
For example this works
```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v3.json",
  "data": {
    "url": "myfile.csv"
    },
    "Rest of specification"
}
```
While this doesn't
```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v3.json",
  "layer": [
    {
      "data": {
      "url": "myfile.csv"
      },
      "Rest of specification"
}
```

**Comment by Corvince** [comment]
Somewhat related: I tried to start a local http server and included 
`"url": "http://127.0.0.1:8000/myfile.csv"`
This also doesn't work, but it doesn't say "myfile.csv not found"

**Comment by RandomFractals** [comment]
Loading data from a web server currently works only via https due to Content-Security-Policy I have set for secure data transfers.

I'll add local data loading for layers in the next patch release update.

Thanks for pointing that out.

**Comment by RandomFractals** [comment]
@Corvince this can now be worked out with http patch in v2.2.0 and instructions I added to #16 for simple hosting of your local data files: https://github.com/RandomFractals/vscode-vega-viewer/issues/16#issuecomment-463197623

I'll still add relative local data files load for layers in the next patch, but it should not be a major showstopper for you to use this ext. now for authoring Vega json specs with layers data references.

**Comment by RandomFractals** [comment]
@Corvince I am having hard time finding a vega or vega-lite example where layered data is used. I flipped through a hundred examples and pretty much all use top level data config.

Can you get the latest v3.0 of this ext. with built-in examples and point me to a working example with layered data url elements?

**Comment by Corvince** [comment]
Built-in examples in V3 work great, but I can't point you to a working example, because they don't work ;) 

Most `geo_*` examples use layerd data, e.g. `geo_layer.vl.json` ;)

**Comment by RandomFractals** [comment]
> 
> 
> Built-in examples in V3 work great, but I can't point you to a working example, because they don't work ;)
> 
> Most `geo_*` examples use layerd data, e.g. `geo_layer.vl.json` ;)

@Corvince Perfect! we'll make them work! I just could not find a good example using it.

Happy to hear you like built-in examples for quick starters and exploring community contributed vega jsons.

**Comment by RandomFractals** [comment]
@Corvince this should now work for all local/relative data references in vega spec. I am aware of.

Please review this patch update code here if you'd like: https://github.com/RandomFractals/vscode-vega-viewer/commit/8d49d4e309892a0aea9b19379dec9ae99b0ec591#diff-5c245625569aa17bdc70402dfc2e4504

and let me know if there are any other edge cases I've missed for this feature request.

**Comment by Corvince** [comment]
Hey there, after quite some delay I just wanted to say thank you! Both locally hosted data and "layered" data work like a charm!
