### ISSUE TITLE
[feature question] `Logs`, `Data Viewer` panel

### ISSUE THREAD

**Issue by HaveF** [RandomFractals/vscode-vega-viewer#155]
Hi, RandomFractals, ❤️ 

Thanks for your work! It helps me a lot.

I was wondering do we have `Logs`, `Data Viewer`, `Signal Viewer` panel etc like in https://vega.github.io/editor/#/

If not, do we have any plan about it? Thanks!

**Comment by RandomFractals** [comment]
Not in the latest version of Vega Viewer. I believe you requested this in #151 already.

Currently, there are no plans to add it as Vega Viewer integrates with Data Preview for the loaded data.

I can see how adding Signal Viewer might be useful, but Vega Viewer user base is rather small, and I believe most users use the viewer and online editor at the same time already while prototyping vega and vega-lite charts.

Related #154.

**Comment by HaveF** [comment]
🤣🤣🤣 I forget it, thanks for your reply
