### ISSUE TITLE
add vega.help command using browser preview setup to show supporting docs 🤔

### ISSUE THREAD

**Issue by RandomFractals** [RandomFractals/vscode-vega-viewer#33]
this extension already provides `jsonSchema` validation and intelli-sense code hints for `vega` json files.

Adding online help docs loading in another preview panel could be next good step to make it even more appealing for devs using vega viz libs or altair for charting and data viz prototyping.

i.e. something as simple as just loading vega examples site in another vscode preview panel to alleviate the need to load vega docs in chrome or other browser window:

https://vega.github.io/vega/examples/contour-plot/

cc @domoritz @kanitw & @jheer: your thoughts on this?

**Comment by domoritz** [comment]
I haven't felt the need for it but then I am also not the average user.
