### ISSUE TITLE
add an official vega lib extension icon

### ISSUE THREAD

**Issue by domoritz** [RandomFractals/vscode-vega-viewer#34]
Based on https://github.com/vega/logos maybe?

**Comment by RandomFractals** [comment]
will do! are those final now? thx for the links to your icons set!

@domoritz if I do that, will you flag Vega Viewer with a 🌟 as a "featured plugin/tool" in your vega-lite ecosystem doc? 😏

https://vega.github.io/vega-lite/ecosystem.html

also, I think you should remove a link to the defunct Vega Preview vscode ext. there. It's a dud and just makes it confusing for devs looking to use your libs in vscode.

**Comment by domoritz** [comment]
Sure, send us a PR to update the ecosystem page. Thanks!

**Comment by RandomFractals** [comment]
Actually, I'm gonna roll in my own custom VV icon for this ext., not to be confused with VL || AL 'ribbon' icons you guys have created for your Vega libraries.

I'll leave it up to you if you want to feature Vega Viewer higher up on the tools list with a star for the featured bit. 

P.S.: You know I don't PR & would appreciate if you stopped asking me about it :) I thought we covered that before...

**Comment by RandomFractals** [comment]
most likely it will be something like this: 💹

more info here: https://twitter.com/TarasNovak/status/1161617325356965891
