### ISSUE TITLE
png export link toolbar wrapping issue

### ISSUE THREAD

**Issue by domoritz** [RandomFractals/vscode-vega-viewer#36]
The css probably needs to be adjusted

<img width="227" alt="Screen Shot 2019-06-20 at 17 11 51" src="https://user-images.githubusercontent.com/589034/59888927-bdbdb680-937e-11e9-885c-e318b9716db2.png">

**Comment by RandomFractals** [comment]
perhaps. what vscode & vscode theme was this screenshot taken with?

VV has not see any updates in a month. Last it was tested with vscode v1.34.0 I believe. see https://github.com/microsoft/vscode/releases/tag/1.34.0

I'll patch it later this month. 

Any other updates to your Vega libs I should pull in that patch release?

**Comment by domoritz** [comment]
I'm using the latest vscode with the solarized color theme on mac os. Maybe the dropdown is a bit larger on OSX.

**Comment by RandomFractals** [comment]
most likely. Unfortunately, I am not on a Mac. 

I'll change those export links to Save dropdown in the next v. update and set better/explicit sizing for that side bar.

Thanks for letting me know about this.

Any new updates to your Vega libs I should grab for that patch release?

**Comment by domoritz** [comment]
You can always update to the latest versions.

**Comment by RandomFractals** [comment]
@domoritz I added 10 more pixels for that side bar for now.

Vega libraries have been updated to latest. see changes in ticket #37
