### ISSUE TITLE
Dropdown are offset on MacOS

### ISSUE THREAD

**Issue by domoritz** [RandomFractals/vscode-vega-viewer#50]
The text in the dropdown is slightly offset on macOS. The dropdown also jump when something is selected.

![Kapture 2019-11-11 at 17 22 47](https://user-images.githubusercontent.com/589034/68633783-f97d2800-04a7-11ea-8840-9a7a9332b8b5.gif)

**Comment by RandomFractals** [comment]
so, data dropdown is 2 px? lower then the theme & save dropdowns?

Thank you for reporting this. You did mention it in your slack before.

I do consider it a minor Mac UI glitch & unless other devs find it really disturbing I will look into it per other issues priority list ...

**Comment by domoritz** [comment]
The text in the first dropdown above is also cut off. I find it disturbing ;-)

**Comment by RandomFractals** [comment]
is this a continuation of your #53 complaints?

**Comment by domoritz** [comment]
The solution in #53 would fix this issue but this is an orthogonal bug.

**Comment by RandomFractals** [comment]
I would call it an orthopedic if you want to go that far ;)

**Comment by RandomFractals** [comment]
see: https://github.com/RandomFractals/vscode-vega-viewer/issues/51#issuecomment-565096860
