### ISSUE TITLE
UI suggestions: use title before dropdowns

### ISSUE THREAD

**Issue by domoritz** [RandomFractals/vscode-vega-viewer#53]
I would like to suggest a simple UI change where you add a text in front of the dropdown instead of as the first item in the dropdown. 

For the export, I would suggest not using a dropdown and instead using two buttons. I have never seen an action being executed when I select an item in a dropdown.

**Comment by RandomFractals** [comment]
@domoritz thank you for your suggestions, but this is consistent with other vscode dataViz extensions I've developed & I plan to keep those data, themes & save dropdows with custom emojies that way ;)

**Comment by domoritz** [comment]
It makes sense if this is a common pattern. Can you show me some of those extensions?

**Comment by RandomFractals** [comment]
sure, see here: https://github.com/RandomFractals/vscode-data-preview

also, this UX stuff in the tooling I do for you guys in that tiny toolbar ribbon is not really up for discussion. There are some UX standards vscode devs & others use that might not be to your liking.

I'd rather you shared the posts & tweets about those updates than nitpicking here ...

**Comment by domoritz** [comment]
Can you send me a link to an extension that isn't yours?

**Comment by RandomFractals** [comment]
@domoritz this is not what this repo is for. Sorry if you don't like dropdowns. I can link you to dev to posts on it when I get to it ;)

**Comment by domoritz** [comment]
I guess I still disagree that dropdowns are the best UI pattern here.

**Comment by RandomFractals** [comment]
sure, we can agree to disagree. now, get on with it!

Share this with your devs & vega-vis twitter followers if you have some time on your hands ;) https://dev.to/tarasnovak/visual-studio-code-vega-viewer-5gi6

There were more I DM'ed you ...

**Comment by domoritz** [comment]
We are listing your extension at https://vega.github.io/vega-lite/ecosystem.html#pl and it's advertised on Slack.

**Comment by RandomFractals** [comment]
good. maybe RT that last VV v. update from your vega-vis twitter handle. thx!

**Comment by domoritz** [comment]
https://twitter.com/vega_vis/status/1194083315260821504
