### ISSUE TITLE
Support base url

### ISSUE THREAD

**Issue by domoritz** [RandomFractals/vscode-vega-viewer#54]
This is a feature request. 

It would be sweet if the viewer supported setting the base URL. I am trying to use the viewer in the Vega repo and it doesn't find the dataset for the chart I am trying to look at. 

<img width="1375" alt="Screen Shot 2019-11-11 at 18 38 08" src="https://user-images.githubusercontent.com/589034/68637133-888f3d80-04b2-11ea-90a3-23de049aebc2.png">

**Comment by RandomFractals** [comment]
that's an interesting q. However, why overload this ext. with redundant local data ref settings? 

I think the 2 options available are really simple to keep up with:

1. you specify http(s) data end-point & we load it from a public data source

||

2. you are using local data snapshot & should just change your local data file relative path in your vega spec.

so, I do think this is already as simple as it gets & I am gonna close this issue b/c I don't want to overcomplicate this ext. settings. 

P.S.: Do try built-in examples!  your iris is there too! :)

**Comment by domoritz** [comment]
Okay. Maybe Vega should add a symlinked data directory then.

I tried the examples.

**Comment by RandomFractals** [comment]
well, that's up to you, but I think our job is done here as far as this vscode ext. & your vega specs & data sets/refs go :)
